#!/usr/bin/python3

from tkinter import *
import tkinter

eltrans = Tk()
eltrans.title("Eltrans")

w = Listbox ( eltrans )
w.insert(1, "1")
w.insert(2, "2")
w.insert(3, "3")
w.pack()

def get():
    global hi
    hi = w.curselection()
Button(eltrans, text="OK", command=get).pack()

eltrans.mainloop()
