#!/usr/bin/python3

from tkinter import *
from subprocess import Popen as r
from subprocess import PIPE
import sys

Label(eltransGO, text="Installing dependencies...").pack()
r(["gksu", "apt install <PutDependenciesHere>"], shell=False, stdout=sys.stdout, stderr=sys.stdout)
eltransGO = Tk()

eltransGO.mainloop()
